[package]
name = "finance-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sha-1 = "0.10"
base64 = "0.21"
socket2 = "0.5"
rand = "0.8"


[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "websocket"
path = "src/bin/websockets.rs"